DEBUG = True

SECRET_KEY = 'dev_key_h8hfne89vm'

MEDIA_MERGED = False

UPS_API_USERNAME = ''
UPS_API_PASSWORD = ''
FEDEX_API_USERNAME = ''
FEDEX_API_PASSWORD = ''
USPS_API_USERNAME = ''
USPS_API_PASSWORD = ''
DHL_API_USERNAME = ''
DHL_API_PASSWORD = ''

# OAuth settings
FACEBOOK_APP_ID = ''
FACEBOOK_APP_SECRET = ''

GOOGLE_CLIENT_ID = ''
GOOGLE_SECRET = ''
