DEBUG = True

SECRET_KEY = 'dev_key_h8hfne89vm'

MEDIA_MERGED = False

UPS_API_USERNAME = 'computmaxer'
UPS_API_PASSWORD = 'Lr4zIWECQVeJ'
FEDEX_API_USERNAME = 'Bwc8CnbPXQHuvCd4'
FEDEX_API_PASSWORD = 'Y1pWLAQKK7W15t4rC2F9H6pVk'
USPS_API_USERNAME = '600PHDJA7339'
USPS_API_PASSWORD = '891BS74QT359'
DHL_API_USERNAME = 'DServiceVal'
DHL_API_PASSWORD = 'testServVal'
